version: '3'
services:
  localstack:
    container_name: localstack-tests
    ports:
      - "4566-4599:4566-4599"
    environment:
      - AWS_ACCESS_KEY_ID=any
      - AWS_SECRET_ACCESS_KEY=anu
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_DEFAULT_ACL=None
      - DATA_DIR=./localstack/data:/tmp/localstack/data
      - SERVICES=sqs,dynamodb,lambda,cloudwatch,cloudformation,s3,iam,appconfig,sts,ec2,kms,stepfunctions,secretsmanager
      - LAMBDA_EXECUTION=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
      - DYNAMO_SHARE_DB=1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
    volumes:
      - ./localstack/data:/tmp/localstack/data
    image: localstack/localstack:latest
  stepfunctions:
    container_name: stepfunctions-tests
    image: amazon/aws-stepfunctions-local:latest
    environment:
      - AWS_ACCESS_KEY_ID=any
      - AWS_SECRET_ACCESS_KEY=any
      - AWS_DEFAULT_REGION=sa-east-1
      - LAMBDA_ENDPOINT=http://host.internal.docker:4566
      - DYNAMO_ENDPOINT=http://host.internal.docker:4566
      - S3_ENDPOINT=http://host.internal.docker:4566
      - SFN_MOCK_CONFIG=/tmp/state_machine_mocks.json
    ports:
      - "8083:8083"
    volumes:
      - "./state_machine_mocks.json:/tmp/state_machine_mocks.json"
    cors:
      build: .
      container_name: cors
      ports:
        - "8084:80"
 